public array $default = [
    'DSN'          => '',
    'hostname'     => env('database.default.hostname', 'localhost'),
    'username'     => env('database.default.username', ''),
    'password'     => env('database.default.password', ''),
    'database'     => env('database.default.database', ''),
    'DBDriver'     => env('database.default.DBDriver', 'MySQLi'),
    'DBPrefix'     => '',
    'pConnect'     => false,
    'DBDebug'      => ENVIRONMENT !== 'production',
    'charset'      => 'utf8mb4',
    'DBCollat'     => 'utf8mb4_general_ci',
    'swapPre'      => '',
    'encrypt'      => false,
    'compress'     => false,
    'strictOn'     => false,
    'failover'     => [],
    'port'         => (int) env('database.default.port', 3306),
    'numberNative' => false,
    'foundRows'    => false,
    'dateFormat'   => [
        'date'     => 'Y-m-d',
        'datetime' => 'Y-m-d H:i:s',
        'time'     => 'H:i:s',
    ],
];